version: '3.8'
services:
  web:
    image: nginx-https
    ports:
      - "81:81"
      - "443:443"
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ./nginx.html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
  apache:
    image: php:7.2-apache
    ports:
      - "80:80"
    volumes:
      - ./info.php:/var/www/html/info.php
