version: '3.8'
services:
  web:
    image: ng
    ports:
      - "80:81"
      - "443:443"
      - "8081:8081"
      - "8082:8082"
    volumes:
      - ./nginx.html:/usr/share/nginx/html/nginx.html
      - ./nginx.conf:/etc/nginx/nginx.conf
