version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8080:80"
    volumes:
      - ./nginx.html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf

  apache:
    build: ./apache
    container_name: apache_container
    volumes:
      - ./html/apache:/usr/local/apache2/htdocs/
